<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" lang="pt_BR">
		<head>
			<title>Cedup - Almoxarifado</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
			<link type="text/css" href="app.misc/css/menu.css" rel="stylesheet" ></link>
                        <link type="text/css" href="app.misc/css/redmond/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
                        <link type="text/css" href="app.misc/css/login.css" rel="stylesheet" ></link>
			<link href="app.misc/css/style.css" rel="stylesheet" type="text/css" ></link>
			<script type="text/javascript" src="app.misc/js/jquery.js"></script>
			<script type="text/javascript" src="app.misc/js/menu.js"></script>
                        <link type="text/css" href="app.misc/css/redmond/jquery-ui-1.8.16.custom.css" rel="stylesheet" ></link>
                        <script type="text/javascript" src="app.misc/js/jquery-1.6.2.min.js"></script>
                        <script type="text/javascript" src="app.misc/js/jquery-ui-1.8.16.custom.min.js"></script>
                        <script type="text/javascript" src="app.misc/js/script.js"></script>
                        <link href="app.misc/css/estilo.css" type="text/css" rel="stylesheet" title="CSS" principal="" media="all"></link>
			
		</head>
	<body>
		<div id="corpo">
			<div id="topo">
					
			</div>
				<div id="menu">
					<ul class="menu">
                                            <li><a href="index.php" class="parent"><span>Panel</span></a></li>
                                            <li><a href="#"><span>Informações</span></a></li>
                                            <li class="last"><a href="#"><span>Contatos</span></a></li>
                                            <?php if ($sessao->getVar('usuario') == null){
                                                echo '<li class="login"><a href="index.php"><span>Login</span></a></li>';
                                            }else{
                                                echo '<li class="login"><a href="index.php?&logout=1"><span>Logout</span></a></li>';
                                            }?>  
                                        </ul>
                                </div>
                                <?php if ($flashes){ ?>
                                <div id="alert">
                                    <p><span class="ui-icon ui-icon-alert" style="float:left;"></span> <?php echo $flashes ?></p>
                                </div>    
                                <?php } ?>  
                                            
                                <div id="content">
                                        <?php 
                                                if (isset($templatePage)){
                                                require $templatePage;
                                                }else{
                                                echo('Template não encontrado');

                                        } ?>

                                </div>
			<div id="rodape">
				<p>2012 © Copyright Cedup, All rights reserved</p>
			</div>
		</div>
	</body>
</html>
