<div id="tdiv">
    <h1>Laboratório</h1>
    <form method="POST" action="">
        <label>Laboratório:</label>
        <input class="campo" size="30" type="text" name="nome_laboratorio" value="" />
        <label>Número:</label>
        <input class="campo" size="3" type="text" name="numero_laboratorio" value="" />
        <input id="bt" type="submit" name="saveLab" value="Salvar" />
        <input class="btCancel" onclick="javascript:location='index.php?modulo=chaves&page=visualizar'" type="button" name="voltar" value="Voltar" />
    </form>         
</div>