        <div class="main">
            <div id="tdiv">
                <h1>Cadastro</h1>    
                <form id="frm" method="POST" action="">

                    <label>Nome:</label>
                    <input id="sf_nome" class="campo" type="text" style="width:210px;" id="login" name="nome_usuario" value=""/>
                    
                    <label>Tipo:</label>
                    <select id="sf_tipo" class="campo" name="tipo_usuario_id">
                            <option value="0"></option>
                    <?php foreach ($tipos_usuarios as $tipo) {
                          echo "<option value={$tipo['id_tipo']}>{$tipo['nome_tipo']}</option>\n";  
                    } ?> 
                    </select>
                    
                    <label>Email:</label>
                    <input id="sf_email" class="campo" type="text" style="width:210px;" name="email_usuario" value=""/>
                    
                    <label>Telefone:</label>
                    <input id="sf_tel" class="campo" type="text" style="width:105px;" maxlength="8" name="telefone_usuario" value=""/>
                    
                    <label>Celular (Opcional):</label>
                    <input id="sf_celurar" class="campo" type="text" style="width:105px;" maxlength="8" name="celular_usuario" value=""/>
                    
                    <label>Data Nascimento:</label>
                    <input id="datepicker" class="campo" type="text" style="width:105px;" name="dt_nascimento_usuario" value=""/>
                    
                    <label>Login:</label>
                    <input id="sf_login" class="campo" style="width:210px;" type="text" name="login_usuario" value=""/>
                    
                    <label>Senha:</label>
                    <input class="campo" style="width:210px;" type="password" name="senha_usuario" value=""/>
                    
                    <label>Repetir a Senha:</label>
                    <input class="campo" style="width:210px;" type="password" name="confirma_senha" value=""/>
                    
                    <input align="center" id="bt" type="submit" name="save" value="Cadastrar"/>

                </form>
            </div>
            
        </div>

