<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" lang="pt_BR">
		<head>
			<title>Cedup - Almoxarifado</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8">                        
<?php
foreach(TApplication::$styleLink as $style)
    echo '			<link type="text/css" href="app.misc/css/'.$style.'.css" rel="stylesheet" />',"\n";
foreach(TApplication::$scriptLink as $script)
    echo '			<script type="text/javascript" src="app.misc/js/'.$script.'.js"></script>',"\n";
?>
		</head>
	<body>   
                <div id="corpo">
                    
                    <?php if(isset($usuario->permissoes)) $menu->show(); ?>
			<div id="topo">
					
			</div>
                        <?php if(isset($usuario)){ ?>
                            <div onclick="zerar()" id="controler_bar">
                                <span><a href="index.php">Painel</a></span>
                                <div>
                                    <a href="index.php?modulo=usuarios&page=info-usuario">
                                    <div>
                                          <p><?php echo $sessao->getVar('usuario')->nome_usuario; ?></p>
                                    </div>
                                    </a>    
                                    <a href="index.php?modulo=usuarios&page=logout"><div><p>Logout</p></div></a>
                                </div>
                            </div>
                        <?php }else{ ?>
                            <div onclick="zerar()" id="controler_bar_login">
                                <span><a href="index.php">Inicio</a></span>
                            </div>
  
                        <?php } ?>  
                    
                            <?php if ($flashes){ ?>
                                <div id="alert" class="ui-icon-alert" style="text-align:left; margin-left:0 auto">
                                    <p><span style="float:left;"></span> <?php echo $flashes ?></p>
                                </div>    
                                <?php } ?>  
                                            
                                <div id="content">
                                        <?php 
                                                if (isset($templatePage)){
                                                require $templatePage;
                                                }else{
                                                echo('Template não encontrado');

                                        } ?>

                                </div>
			<div id="rodape">
			</div>
		</div>
	</body>
</html>
