<div id="headerPage">
    <span>Minhas manutenções</span>
</div>
<table align="center" class="table">
    <thead align="left">
        <tr>
            <th width="40">Código</th>
            <th width="170">Requisitante</th>
            <th width="80">Data</th>
            <th width="150">Status</th>
            <th>Detalhes</th>
                   
        </tr>
     </thead>
      <?php
    
    if (isset($requisicoes[0])){
      
	    $i = 0;
	    foreach($requisicoes as $requisicao){
	    
	    $databr = Utils::formatDateBr($requisicao->dt_requisicao);    
	        
	    $bgcolor = ($i % 2) == 0 ? '#ffffff' : '#e0e0e0';    
	    
	    echo "<tr>
	              <td align=center bgcolor={$bgcolor}>{$requisicao->id_requisicao}</td>
	              <td align=left bgcolor={$bgcolor}>{$requisicao->nome_usuario}</td>
	              <td align=left bgcolor={$bgcolor}>{$databr}</td>
	              <td align=left bgcolor={$bgcolor}>{$requisicao->nome_estado_requisicao}</td>
	              <td align=center bgcolor={$bgcolor}><a title='Exibir detalhes' href='index.php?modulo=manutencoes&page=visualizar&m-manu=1&key={$requisicao->id_requisicao}'>
	                                     <img src='app.misc/images/ico_produtos.png'></a></td>";
	             
	    
	     echo "</tr>";
	    $i = $i+1;
	    
	    } 

    }else{
    	echo "<tr bgcolor='#FFFFFF'>
    			<td align='center' colspan = 5 >Você não tem manutenção pendente.</td> 
    		 </tr>";
    }
    
    ?>
    
     </tbody>
</table>
<button style="margin-top:15px;" name="busca" onclick="javascript:location='index.php'">Voltar</button>

