 <div id="tdiv">
                <h1>Requerir manutenção</h1>    
                <form method="POST" action="">

                    <label>Data atual:</label>
                    <input class="campo" type="text" readonly="readonly" style="width:105px" name="dt_requisicao" value="<?php echo Utils::getDate()?>"/>
                    
                    <label>Requisitante:</label>
                    <input class="campo" type="text" readonly="readonly" style="width:200px" name="nome_requisitante" value="<?php echo $sessao->getVar('usuario')->nome_usuario;?>"/>
                    
                    <label>Equipamento(s):</label>
                    <textarea cols="23" rows="6" maxlength="100" class="campo" name="equipamento_requisicao" value=""><?php if (isset($requisicoes)){echo ($requisicoes['equipamento_requisicao']);}?></textarea>
                    
                    <label>Localização(s):</label>
                    <textarea cols="23" rows="6" maxlength="100" class="campo" name="local_equipamento" value=""><?php if (isset($requisicoes)){echo ($requisicoes['local_equipamento']);}?></textarea>
                    
                    <label>Defeito(s):</label>
                    <textarea cols="23" rows="6" maxlength="100" class="campo" name="defeito_requisicao" value=""><?php if (isset($requisicoes)){echo ($requisicoes['defeito_requisicao']);}?></textarea>
                        
                    
                    <input style="margin-left:35%; margin-bottom:20px;" type="submit" name="<?php echo (isset($id))? 'update' : 'save' ?>" value="Requerir"/>
                    <input type="button" name="edit" value="Voltar" onclick="javascript:location='<?php echo (isset($id))? 'index.php?modulo=manutencoes&page=visualizar' : 'index.php' ?>'"/>
                </form>
         </div>
         
