<div id="headerPage">
    <span>Manutenções Pendentes</span>
</div>
<form method="POSt" action="">
    <label>Status:</label>
    <select name="estadoBusca">
        <option value="todos">Todas</option>
        <?php 
   
        foreach ($estados as $estado) {
        	if ($estado['id_estado_requisicao'] != 4 and $estado['id_estado_requisicao'] != 5){
                echo "<option value={$estado['id_estado_requisicao']}";
                   
                    if (isset($_POST['busca'])){
                        if ($estado['id_estado_requisicao'] == $_POST['estadoBusca']){
                            echo ' selected="selected"'; 
                        }
                    }
                    
                    if (array_key_exists('estado',$_GET)){
                        if ($estado['id_estado_requisicao'] == $sessao->getVar('estado')){
                            echo ' selected="selected"';
                            $sessao->removeVar('estado');
                        }
                    }
                    
                    
                echo ">{$estado['nome_estado_requisicao']}</option>\n";
        	}  
        }   
        ?> 
        
    </select>
    <input type="submit" value="Buscar" name="busca"/>
    <input type="button" value="Voltar" name="busca" onclick="javascript:location='index.php'"/>
    
</form>

<table id="table" style="margin-top:30px;" align="center" class="table">
    <thead align="left">
        <tr>
            <th width="40">Código</th>
            <th width="170">Requisitante</th>
            <th width="80">Data</th>
            <th width="150">Status</th>
            <th>Detalhes</th>
            <th></th>
            <th></th>
        </tr>
     </thead>
     <tbody align="left">
    <?php 
    
    if (isset($requisicoes[0])){
	    $i = 0;
	    foreach($requisicoes as $requisicao){
	    
	    $databr = Utils::formatDateBr($requisicao->dt_requisicao);    
	        
	    $bgcolor = ($i % 2) == 0 ? '#ffffff' : '#e0e0e0';    
	    
	    echo "<tr bgcolor={$bgcolor}>
	              <td>{$requisicao->id_requisicao}</td>
	              <td>{$requisicao->nome_usuario}</td>
	              <td>{$databr}</td>
	              <td>{$requisicao->nome_estado_requisicao}</td>
	
	              <td align=center ><a title='Exibir detalhes' href='index.php?modulo=manutencoes&page=visualizar&key={$requisicao->id_requisicao}'>
	                                     <img src='app.misc/images/ico_produtos.png'></a></td>";
	              
	              
	              if ($requisicao->estado_id == 1){
	              
	              echo "<td align=center ><a title='Editar requisição' href='index.php?modulo=manutencoes&page=requerir&key={$requisicao->id_requisicao}'>
	                                     <img src='app.misc/images/ico_edit.png'></a></td>
	                   <td align=center ><a class='open-link-delete' title='Excluir requisição' href='index.php?modulo=manutencoes&page=visualizar&req-key={$requisicao->id_requisicao}'>
	                                     <img src='app.misc/images/ico_delete.png'></a></td>";  
	                  
	              }else{
	                  echo "<td>&nbsp</td>
	                        <td>&nbsp</td>";
	              }
	              
	     echo "</tr>";
	    $i = $i+1;
	    }
    }else{
    	echo "<tr bgcolor='#FFFFFF'>
    	<td align='center' colspan = 7 >Nenhuma requisição encontrada.</td>
    	</tr>";
    }
     
       
    
    ?>
    
     </tbody>
</table>

<div id="janela-delete">
        <form id="form-delete" class="form" name="frm" method="post" action="">
            <fieldset>
                 Deseja deletar esta requisição?
            </fieldset>
        </form> 
</div>
