<div class="tpanel">
    
    <fieldset width=200>
        <legend>Info. pessoais</legend>
        
        <div class="allmenu">
            <div class="header">
                <label>Editar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=Usuarios&page=info-usuario"><img class="img" src="app.misc/images/clipboard_cut_48_h.png" ></a>
            </div>
        </div>
    
    </fieldset>
    <fieldset width=200>
        <legend>Usuários</legend>
    
        <div class="allmenu">
            <div class="header">
                <label>Visualizar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=usuarios&page=list-usuario"><img class="img" src="app.misc/images/users_32.png" ></a>
            </div>
        </div>
        
    </fieldset>
    
    <fieldset width=200>
        <legend>Manutenção</legend>
        <div class="allmenu">
            <div class="header">
                <label>Requerir</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=manutencoes&page=requerir"><img class="img" src="app.misc/images/infoMenu.png" ></a>
            </div>
        </div>
        
        <div class="allmenu">
            <div class="header">
                <label>Visualizar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=manutencoes&page=requerir-visualizar"><img class="img" src="app.misc/images/infoMenu.png" ></a>
            </div>
        </div>
    </fieldset>
</div>