<div class="tpanel">

    <fieldset width=200>
        <legend>Usuários</legend>
    
        <div class="allmenu">
            <div class="header">
                <label>Visualizar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=usuarios&page=visualizar"><img class="img" src="app.misc/images/users_256.jpg" ></a>
            </div>
        </div>
        
    </fieldset>
    
    <fieldset width=200>
        <legend>Manutenção</legend>
        <div class="allmenu">
            <div class="header">
                <label>Requerir</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=manutencoes&page=requerir"><img class="img" src="app.misc/images/folders_48_h.png" ></a>
            </div>
        </div>
        
        <div class="allmenu">
            <div class="header">
                <label>Visualizar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=manutencoes&page=visualizar"><img class="img" src="app.misc/images/search_48.png" ></a>
            </div>
        </div>
        
        <div class="allmenu">
            <div class="header">
                <label style="font-size:11.1pt">Manutenções</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=manutencoes&page=m-manutencoes"><img class="img" src="app.misc/images/chave.jpg" ></a>
            </div>
        </div>
    </fieldset>
    <fieldset width=200>
        <legend>Chaves</legend>
        
        <div class="allmenu">
            <div class="header">
                <label style="font-size:11.1pt">Visualizar</label>
            </div>
            <div class="menu">
                <a href="index.php?modulo=chaves&page=visualizar"><img class="img" src="app.misc/images/chaveiro02.jpg" ></a>
            </div>
        </div>
    </fieldset>
</div>
