<h1> Detalhes da Requisicão </h1>

<table class="detail" align="center">
    <tr>
        <th>Requisitante</th>
        <td><?php echo $requisicao->nome_usuario; ?><td>
    </tr>
    <tr>
        <th>Data</th>
        <td><?php echo Utils::formatDateBr($requisicao->dt_requisicao); ?><td>
    </tr>
    <tr>
        <th>Equipamento</th>
        <td><?php echo $requisicao->equipamento_requisicao; ?><td>
    </tr>
    <tr>
        <th>Defeito</th>
        <td><?php echo $requisicao->defeito_requisicao; ?><td>
    </tr>
    
    <tr>
        <th>Localização</th>
        <td><?php echo $requisicao->local_equipamento; ?><td>
    </tr>
    
    <tr>
        <th>Status</th>
        <td><?php echo $requisicao->nome_estado_requisicao; ?><td>
    </tr>
    <tr>
        <th colspan="2">&nbsp</th>
    </tr>   

</table>

<form action="" method="POST">
    <table class="detail" align="center">
        <tr>
            <th>Resp. Manutenção</th>
            <td><input readonly="readonly" type="text" name="nome_usuario" value="<?php echo $sessao->getVar('usuario')->nome_usuario;?>"/></td>
        </tr>
        <tr>
            <th>Data da Manutenção</th>
            <td><input type="text" name="data_manutencao" value="<?php echo Utils::getDate();?>"/></td>
        </tr>
        <tr>
            <th>Providência:</th>
            <td><textarea cols="24" rows="5" name="providencia_manutencao" value=""></textarea></td>
        </tr>
        <tr>
            <th></th>
            <td><input class="actions" type="submit" value="Confirmar" name="confirm"/>
                <a class="actions" href='index.php?modulo=manutencoes&page=requerir-detail&key=<?php echo $requisicao->id_requisicao;?>'>Cancelar</a></td>
        </tr>

    </table>
</form>