<table align="center" class="table">
    <thead align="left">
        <tr>
            <th width="40">Código</th>
            <th width="170">Requisitante</th>
            <th width="80">Data</th>
            <th width="150">Status</th>
            <th>Detalhes</th>
            <th>Concluir</th>
            

        </tr>
     </thead>
      <?php 
    $i = 0;
    foreach($requisicoes as $requisicao){
    
    $databr = Utils::formatDateBr($requisicao->dt_requisicao);    
        
    $bgcolor = ($i % 2) == 0 ? '#ffffff' : '#e0e0e0';    
    
    echo "<tr>
              <td align=center bgcolor={$bgcolor}>{$requisicao->id_requisicao}</td>
              <td align=left bgcolor={$bgcolor}>{$requisicao->nome_usuario}</td>
              <td align=left bgcolor={$bgcolor}>{$databr}</td>
              <td align=left bgcolor={$bgcolor}>{$requisicao->nome_estado_requisicao}</td>

              <td align=center bgcolor={$bgcolor}><a title='Exibir detalhes' href='index.php?modulo=manutencoes&page=requerir-detail&m-manu=1&key={$requisicao->id_requisicao}'>
                                     <img src='app.misc/images/ico_produtos.png'></a></td>
              <td align=center bgcolor={$bgcolor}><a class=open-link title='Concluir Manutenção' href='index.php?modulo=manutencoes&page=realizar&key={$requisicao->id_requisicao}'>
                                     <img src='app.misc/images/ico_ok.gif'></a></td>";
    
     echo "</tr>";
    $i = $i+1;
    }    
    
    ?>
    
     </tbody>
</table>
    
    <div id="janela-dialog">
        <form id="form-dialog" class="form" name="frm" method="post" action="">
            <fieldset>
                <label>Comentário:</label>
                <textarea class="campo" name="comentario_manutencao" ></textarea>
            </fieldset>
        </form> 
    </div>  

